version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'AmazonProductDatabase'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'Kabil'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Electronic1702!'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Electronic1702!'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  app:   
    build: C:\Users\rajuk\datamodel
    env_file: .env
    depends_on:
      - db
    networks:     
     - default
    ports:
      - "8082:10001" 
     
  server:
        build:
          context: .
          dockerfile: Dockerfile
        env_file: .env
        networks:
          - default
        ports:
        - "8083:10000"

# Names our volume
volumes:
  my-db:

